# --- General options --- #
url: "https://asvoice.github.io"
baseurl: ""

# 웹사이트 이름 및 설명
title: "Rush Eging Team"
description: "Squid and Code."

# --- Navigation bar options --- #
# 들여쓰기와 콜론(:) 뒤의 경로를 명확히 해야 합니다.
navbar-links:
  Home: ""
  About Me: "aboutme"
  MembErs: "member"
  Eging: "eging"
  Other: "other"
  Tags: "tags"

# 네비게이션 바 아바타 (경로 확인 필수)
avatar: "/assets/img/r2.png"

# --- Footer options --- #
# Some Person을 본인 이름으로 수정하세요.
author:
  name: "Rush Team"

# 하단 웹사이트 링크 표시 이름
url-pretty: "asvoice.github.io"

# --- Misc --- #
disqus: "asvoice"
timezone: "Asia/Seoul"
